
[colors.bright]
black = "0x6272a4"
blue = "0x4a90e2"
cyan = "0xa4ffff"
green = "0x69ff94"
magenta = "0xff92d0"
red = "0xff6e6e"
white = "0xffffff"
yellow = "0xffffa5"

[colors.cursor]
cursor = "0xf8f8f2"
text = "0x1c1c1c"

[colors.normal]
black = "0x1e1e1e"
blue = "0x4a90e2"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xf8f8f2"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x1c1c1c"
foreground = "0xf8f8f2"

[font]
size = 14.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[shell]
args = ["--login"]
program = "/usr/bin/fish"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Windowed"

[window.padding]
x = 20
y = 20
